### ISSUE TITLE
Using two APC min does not work.

### ISSUE THREAD

**Issue by atomic7122** [ArtGateOne/dot2apcmini#3]
Hi, I'm trying to use two identical apc minis with your code. This also has the same port ID. After one pad has established the connection, the second connection is not possible.

Akai APC mini .2 WING 1

Midi IN
[ 'APC MINI', 'Bome MIDI Translator 1', 'APC MINI' ]
Midi OUT
[
  'CoolSoft MIDIMapper',
  'Microsoft GS Wavetable Synth',
  'APC MINI',
  'Bome MIDI Translator 1',
  'APC MINI'
]

Connecting to midi device APC MINI

MidiInWinMM::openPort: error creating Windows MM MIDI input port.

C:\Users\user\Desktop\Akai\1\dot2apcmini2-main\dot2apcmini2\node_modules\@julusian\midi\midi.js:35
    return this.input.openPort(port)
                      ^

Error: Internal RtMidi error
    at Input.openPort (C:\Users\user\Desktop\Akai\1\dot2apcmini2-main\dot2apcmini2\node_modules\@julusian\midi\midi.js:35:23)
    at new Input (C:\Users\user\Desktop\Akai\1\dot2apcmini2-main\dot2apcmini2\node_modules\easymidi\index.js:52:23)
    at Object.<anonymous> (C:\Users\user\Desktop\Akai\1\dot2apcmini2-main\dot2apcmini2\dot2apcmini2.js:103:13)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

**Comment by atomic7122** [comment]
I saw your error message with easymide while troubleshooting further, so the problem seems to be with the library. In the screenshot you seem to be using a workaround for this by sending the signals to another virtual midi device. What is the name of the software for this? Also you write it worked in older versions, is there a possibility to use this version, or are there too many other bugs?

**Comment by ArtGateOne** [comment]
Yes - I know about this problem -
The updated easymidi is convenient if you only connect to one midi device - because there is no problem with different names.
If you have a previous version - just copy the main js file to it and replace the midi device names accordingly.
I will try to add a directory with the older version of easymidi soon, on which the devices are numbered.

**Comment by atomic7122** [comment]
I fixed the problem and rewrote the Easymidi library. Problem was the unique names, although the underlying midi libary supports unique ports. I've added a numbering of the identical ports. Unfortunately, I don't know enough about github. How I can communicate this change to the developer. Also, it probably won't be perfectly programmed, but it works. It wasn't big changes.

const getInputs = () => {
  const input = new midi.input();
  const inputs = [];
  for (let i = 0; i < input.getPortCount(); i++) {
    var counter = 0;
    const portName = input.getPortName(i);
    var numberPortName = portName;
    while(inputs.includes(numberPortName)) {
      counter++;
      numberPortName = portName + counter;
    }
    inputs.push(numberPortName);
  }
  input.closePort();
  return inputs;
}

const getOutputs = () => {
  const output = new midi.output();
  const outputs = [];
  for (let i = 0; i < output.getPortCount(); i++) {
    var counter = 0;
    const portName = output.getPortName(i);
    var numberPortName = portName;
    while(outputs.includes(numberPortName)) {
      counter++;
      numberPortName = portName + counter;
    }
    outputs.push(numberPortName);
  }
  output.closePort();
  return outputs;
}

class Input extends EventEmitter {
  constructor(name, virtual) {
    super();
    this._input = new midi.input();
    this._input.ignoreTypes(false, false, false);
    this._pendingSysex = false;
    this._sysex = [];
    this.name = name;

    this.portNumberedNames = getInputs();

    if (virtual) {
      this._input.openVirtualPort(name);
    } else {
      const numInputs = this._input.getPortCount();
      let found = false;
      for (let i = 0; i < numInputs; i++) {
        if (name === portNumberedNames[i]) {
          found = true;
          this._input.openPort(i);
        }
      }
      if (!found) {
        throw new Error('No MIDI input found with name: ' + name);
      }
    }

class Output {
  constructor(name, virtual) {
    this._output = new midi.output();
    this.name = name;

    this.portNumberedNames = getOutputs();

    if (virtual) {
      this._output.openVirtualPort(name);
    } else {
      const numOutputs = this._output.getPortCount();
      let found = false;
      for (let i = 0; i < numOutputs; i++) {
        if (name === portNumberedNames[i]) {
          found = true;
          this._output.openPort(i);
        }
      }
      if (!found) {
        throw new Error('No MIDI output found with name: ' + name);
      }
    }
  }

**Comment by ArtGateOne** [comment]
Try https://github.com/dinchak/node-easymidi/pulls

**Comment by atomic7122** [comment]
I started pullrequest on : https://github.com/dinchak/node-easymidi/pull/45
