### ISSUE TITLE
Page Selector LED Feedback

### ISSUE THREAD

**Issue by sasanforwardslash** [ArtGateOne/dot2apcmini#5]
Using an APC Mini MK2 

When changing pages, the Green LED turns on but never turns off once I switch to another page, unlike how it works with the MA2 script

**Comment by ArtGateOne** [comment]
If you have the Global Autofix option enabled - this is how it will work - any running executor will be visible on each page until it is off.
Therefore, it is most convenient to disable the Global AutoFix option in Setup / Global Settings.

Please let me know if it helped! :D

**Comment by sasanforwardslash** [comment]
Sorry for the late response, the issue wasn't to do with the executers themselves but the page indicator itself on the right most side, I have linked a video below to demonstrate the difference in MA2 script vs Dot2

[](https://www.youtube.com/watch?v=pc5h3c4yVgA)

as you can see as i change the pages in MA2, the light tells me which page im on, but on dot2, it just turns on green but never turns off so if i go to every page, all page buttons will be on

**Comment by ArtGateOne** [comment]
> Sorry for the late response, the issue wasn't to do with the executers themselves but the page indicator itself on the right most side, I have linked a video below to demonstrate the difference in MA2 script vs Dot2
> 
> as you can see as i change the pages in MA2, the light tells me which page im on, but on dot2, it just turns on green but never turns off so if i go to every page, all page buttons will be on

Unfortunately, I don't see a link to the video. Please contact me through my Facebook page.

This should work, as long as you haven't changed
pageselect = 1; to pageselect = 0;

**Comment by ArtGateOne** [comment]
> Sorry for the late response, the issue wasn't to do with the executers themselves but the page indicator itself on the right most side, I have linked a video below to demonstrate the difference in MA2 script vs Dot2
> 
> as you can see as i change the pages in MA2, the light tells me which page im on, but on dot2, it just turns on green but never turns off so if i go to every page, all page buttons will be on

OK, I see what the problem is - pageselect = 2 right?

It should be fine now!

ps: however, I recommend using mode 1 - and disabling globalfix. It seems to be a more convenient way of working

**Comment by sasanforwardslash** [comment]
Just tested it out and everything works as expected! 

thank you for the quick fix!
